### ISSUE TITLE
Set GPS coordinates

### ISSUE THREAD

**Issue by ghost** [smarnach/pyexiftool#12]
This is a nice wrapper but is there a way to pass GPS coordinates for exiftool to set them?

**Comment by smarnach** [comment]
Currently, there are no dedicated methods for updating EXIF information.  Since exiftool itself is able to do this, you can use [one of the low-level methods](http://smarnach.github.io/pyexiftool/#exiftool.ExifTool.execute_json), to implement this yourself.
