### ISSUE TITLE
missing git tag / github release

### ISSUE THREAD

**Issue by anthraxx** [smarnach/pyexiftool#13]
There are no git tags that result in github automatically creating a release tarball that can be used to download a specific version.
I try to package your tool for a distribution and it would be awesome if you can push release tags like 0.1.29 or something like that so the upstream release tracking and distribution packaging is easier
I think it may be in your interests :smile:

Currently I'm packaging it from HEAD as custom defined version 0.1.29 (the .29 are the current amount of commits). It would be incredibly awesome if you can push a tag which is greater or equal to that version numbers so its not recognized to be an older version :cry: 

hope you push git tags soon,
sincerely,
anthraxx

**Comment by smarnach** [comment]
I added a tag named v0.2.0 -- hope that satisfies your requirements.

**Comment by anthraxx** [comment]
@smarnach wow, indeed, thank you very much! :+1: 
I'm packaging and maintaining your software for Arch Linux (AUR) :smile:

if you add new features or did  lot of development don't forget to push a new tag, i'm watching for the tags and will update the package then!
Thank you very much for this great software

**Comment by smarnach** [comment]
Thanks a lot!  I plan to polish this a bit in the near future.
