### ISSUE TITLE
Using get_tags_batch() always includes the SourceFile field

### ISSUE THREAD

**Issue by mairsbw** [smarnach/pyexiftool#17]
This makes it difficult to easily serialize the output of the return values for use with CSV or the like. I did not expect this in the returned dictionary, and it's not specified in the comments. It should be at least specified in the comments, but I would also argue that it shouldn't be added to the returned data and this function should only return explicitly-requested fields.

**Comment by smarnach** [comment]
@mairsbw This library is just a wrapper for the ExifTool command-line application.  The library will return whatever ExifTool returns, and it happens to include the SourceFile key.  I don't disagree with that decision.

It's also trivial to remove the field.  Just iterate over the list returned by `get_tags_batch()` and call `d.pop("SourceFile")` on each item.
