### ISSUE TITLE
Getting help to install and run pyexiftool?

### ISSUE THREAD

**Issue by ReneHeim** [smarnach/pyexiftool#28]
Dear Author,

I am using the Anaconda distribution of Python and did not manage to run your tool to access the exiftools functions from within Python. Would it be possible to get some assistance?

Thanks for your efforts,

René

**Comment by halloleo** [comment]
I have used `pyexiftool` a while ago and it worked fine for me. Any details of what's going wrong for you? You have installed Phil Harvey's  ExifTool and it is on the path accessible for pyexiftool?

**Comment by ReneHeim** [comment]
Thanks for responding. Yes, I have extracted the exiftools.exe on my main drive and can work with exiftools through the terminal. That part is covered. I am not sure if it is accessible for pyexiftool as I don´t know what this would require. I guess I have to copy the source code folder where my other anaconda modules are? Would this be the entire folder or just a sublevel of it? Or am I thinking the wrong way? Thanks heaps for your help.

**Comment by halloleo** [comment]
Just put `exiftool.py` in the same folder as your Python source code file and then *in your Python code* reference the module with `import exiftool`. If at run time this line does not throw an error you should be good to go.

**Comment by ReneHeim** [comment]
Wow! That was simple. I just did not understand that I just have to use this single function. Thanks so much!! All the best, René

**Comment by Pithikos** [comment]
You can also do `pip install git+http://github.com/smarnach/pyexiftool.git`
